print("📅 Today's Date: July 21, 2025")
print("😊 How I'm Feeling: Excited and curious to learn new things!")
print("🎯 Why I Want to Learn Coding: To build amazing projects, get a great job, and grow as a data scientist.")
print("💌 Message to My Future Self: Keep pushing, keep learning. You've come so far—I'm proud of you!")
print("🔥 Favorite Emoji: 🚀")
